// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SquadManager.Database;

#nullable disable

namespace SquadManager.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220706165324_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SquadManager.Database.Models.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Breeder")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChipNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("SquadManager.Database.Models.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExamExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DogId");

                    b.HasIndex("MemberId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("SquadManager.Database.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("SquadManager.Database.Models.MemberProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BasicCourse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BasicCourseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("CommanderCourse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CommanderCourseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ExaminerCourse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExaminerCourseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("GuideCourse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuideCourseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("HeightCourse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HeightCourseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("HelicopterCourse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HelicopterCourseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("InstructorCourse")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("InstructorCourseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Kpp")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("KppDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("KppExpiration")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("MedicalExamination")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MedicalExaminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MedicalExaminationExpiration")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("MemberProperties");
                });

            modelBuilder.Entity("SquadManager.Database.Models.Dog", b =>
                {
                    b.HasOne("SquadManager.Database.Models.Member", "Owner")
                        .WithMany("Dogs")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SquadManager.Database.Models.Exam", b =>
                {
                    b.HasOne("SquadManager.Database.Models.Dog", "Dog")
                        .WithMany("Exams")
                        .HasForeignKey("DogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SquadManager.Database.Models.Member", "Member")
                        .WithMany("Exams")
                        .HasForeignKey("MemberId");

                    b.Navigation("Dog");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("SquadManager.Database.Models.Member", b =>
                {
                    b.HasOne("SquadManager.Database.Models.MemberProperty", "Properties")
                        .WithOne("Member")
                        .HasForeignKey("SquadManager.Database.Models.Member", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("SquadManager.Database.Models.Dog", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("SquadManager.Database.Models.Member", b =>
                {
                    b.Navigation("Dogs");

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("SquadManager.Database.Models.MemberProperty", b =>
                {
                    b.Navigation("Member")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
